export const ORDER_BUTTON_TYPES = {
    "---Common": "",
    "Confirm": "confirm",
    "Cancel": "cancel",
    "---Order": "",
    "Set order item condiment": "set_condiment",
    "Ser order item supplement": "set_supplement",
    "Repeat order item": "repeat",
    "Plus article": "plus_article",
    "Minus article": "minus_article",
    "Void order item": "void_item",
    "Undo option": "undo_option",
    "Set article message": "set_message",
    "Select discount": "discount",
    "Cancel discount": "discount_cancel",
    "Set seat": "set_seat",
    "Set seat name": "set_seat_name",
    "Pay order": "pay",
    "Search": "search",
    "History": "history",
    "Zoom order list mode": "zoom",
    "Select mode": "select",
    "Set manual price": "manual_price",
    "Set client": "client",
    "Customer history": "cust_history",
    "---Payment": "",
    "Pay with": "pay_with",
    "Split by items": "split_by_items",
    "Split by equal": "split_equal",
    "Split by seat": "split_by_seat",
    "Split by part": "split_by_part",
    //"Split by course": "split_by_course",
    "Reverse split": "reverse_split",
    "Add tips": "add_tips",
    "Add payer": "add_payer",
    "Add client": "add_client",
};