name: CD node

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Compile project
      run: npm i

    - name: Build project
      run: npm run build

